### ISSUE TITLE
`kserve-integration` UAT failed with Method Not Allowed kserve `v0.11`

### ISSUE THREAD

**Issue by NohaIhab** [canonical/kserve-operators#182]
### Bug Description

kserve UAT test is failing with `AssertionError: Failed to get predictions!`

### To Reproduce

```
git clone https://github.com/canonical/bundle-kubeflow.git
cd bundle-kubeflow
juju deploy ./releases/latest/edge/bundle.yaml --trust
```
then follow the [instructions](https://github.com/canonical/charmed-kubeflow-uats#charmed-kubeflow-automated-uats) to run the UATs

### Environment

microk8s 1.25-strict/stable
juju 3.1/stable

### Relevant Log Output
the response to get a prediction from the inferenceservice is:

```shell
{'detail': 'Method Not Allowed'}
```

**Comment by NohaIhab** [comment]
the URL that the request was made to in the UATs is not right. 
Expected: `http://sklearn-iris.test-kubeflow.svc.cluster.local/v1/models/sklearn-iris:predict`
Actual: `http://sklearn-iris.test-kubeflow.svc.cluster.local`

so the `POST` request was hitting the `/` endpoint, and this is why we got `Method Not Allowed`

logs from the kserve deployment pod:
* for root
```
2023-10-04 10:10:37.960 uvicorn.access INFO:     10.1.78.214:0 1 - "POST / HTTP/1.1" 405 Method Not Allowed
```
* for `l/v1/models/sklearn-iris:predict`:
```
2023-10-04 10:13:24.900 uvicorn.access INFO:     10.1.78.214:0 1 - "POST /v1/models/sklearn-iris%3Apredict HTTP/1.1" 200 OK
```

**Comment by Matt-Szymczyk** [comment]
For me your solution still doesn't work. For some reason kserve is adding "-predictor-default" to service url. 
Ex. http://sklearn-iris-predictor-default.user123.svc.cluster.local/
Found solution here https://github.com/kubeflow/examples/blob/master/kserve/kubeflow-e2e-mnist/kubeflow-e2e-mnist.ipynb

`isvc_resp = client.get(ISVC_NAME)
isvc_resp_namespace = isvc_resp['metadata']['namespace']
isvc_resp_name = isvc_resp['metadata']['name']
isvc_url = "http://{}-predictor-default.{}.svc.cluster.local".format(isvc_resp_name, isvc_resp_namespace)
print("Inference URL:", isvc_url)`
