### ISSUE TITLE
Integrate kserve/paddle ROCK v0.11

### ISSUE THREAD

**Issue by misohu** [canonical/kserve-operators#206]
### Context

This task is blocked by https://github.com/canonical/kserve-rocks/issues/18. Simillar integration has been done with pmmlserver https://github.com/canonical/kserve-operators/pull/189.

### What needs to get done

1. Integrate the ROCK with the kserve-operator.
2. Write integration test with paddle example.

### Definition of Done

Rock is integrated with kserve-operator and the tests are passing.

**Comment by ca-scribner** [comment]
https://github.com/canonical/kserve-rocks/issues/18 was merged but we are now blocked by https://github.com/canonical/kserve-rocks/issues/28
