### ISSUE TITLE
No kserve-controller on charmHub

### ISSUE THREAD

**Issue by Yajing-Z** [canonical/kserve-operators#49]
When I want to deploy kserve operators on Charmed Kubeflow, I found there is no kserve-controller application on CharmHub.

$ juju deploy kserve-controller --channel=0.8/stable --trust
ERROR resolving error: The Charm with the given name was not found in the Store.

Please help to upload kserve-controller to CharmHub.

**Comment by DnPlas** [comment]
Thanks for raising this, @AmyHoney . We will push the charm in the following days.

**Comment by beliaev-maksim** [comment]
https://charmhub.io/kserve-controller?channel=0.10/stable
